config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events
  root 'welcome#index'

  get 'characters' => 'characters#index'

  get 'events' => 'events#index'

  get 'search' => 'search#search_results'

  get 'search_results' => 'search#search_results'
  get 'search/search_results' => 'search#search_results' 

 


 

  resources :sentiences
  resources :genders
  resources :factions
  resources :races
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
	belongs_to :race
	belongs_to :gender
	belongs_to :faction

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:show]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show

  end

  # GET /characters/new
  def new
    @character = Character.new
    @races = Race.all
    @factions = Faction.all
    @genders = Gender.all
  end

  # GET /characters/1/edit
  def edit
    @races = Race.all
    @factions = Faction.all
    @genders = Gender.all
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :age, :race_id, :gender_id, :birth_date, :death_date, :faction_id, :birth_location, :bio)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :character_name %>
  </div>

  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age, id: :character_age %>
  </div>

  <div class="form-group">
  <%= form.select :race_id, @races.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a race" } %>
  </div>

  <div class="form-group">
  <%= form.select :gender_id, @genders.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a gender" } %>
  </div>

  <div class="form-group">
    <%= form.label :birth_date %>
    <%= form.number_field :birth_date, id: :character_birth_date %>
  </div>

  <div class="form-group">
    <%= form.label :death_date %>
    <%= form.number_field :death_date, id: :character_death_date %>
  </div>

  <div class="form-group">
  <%= form.select :faction_id, @factions.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a faction" } %>
  </div>

  <div class="form-group">
    <%= form.label :birth_location %>
    <%= form.text_field :birth_location, id: :character_birth_location %>
  </div>

  <div class="form-group">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :character_bio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Race</th>
      <th>Gender</th>
      <th>Birth date</th>
      <th>Death date</th>
      <th>Faction</th>
      <th>Birth location</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.age %></td>
        <td><%= character.race.name %></td>
        <td><%= character.gender.name %></td>
        <td><%= character.birth_date %></td>
        <td><%= character.death_date %></td>
        <td><%= character.faction.name %></td>
        <td><%= character.birth_location %></td>
        <td><%= character.bio %></td>
        <!--<% if can? :update, character %>-->
          <p><%= link_to 'Show', character %></p>
          <p><%= link_to 'Edit', edit_character_path(character) %></p>
          <p><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <!--<% end %>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  
<!--<% if can? :create, Character %>-->
<%= link_to 'New Character', new_character_path %>
<!--<% end %>-->

<!--
  <% @characters.each do |character| %>
    <div class="card" style="width: 20rem;">
      
      <div class="card-body">
        <h3 class="card-title">Name: <%= character.name %></h3>
        <h4 class="card-title">Age: <%= character.age %></h4>
        <h4 class="card-title">Race: <%= character.race.name %></h4>
        <h4 class="card-title">Gender: <%= character.gender.name %></h4>
        <p class="card-text"><%= character.bio %></p>
        <% if can? :update, character %>
          <p><%= link_to 'Show', character %><%= link_to 'Edit', edit_character_path(character) %><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <% end %>
      </div>
    </div>
  <% end %>

-->
      
    

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Race:</strong>
  <%= @character.race.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @character.gender.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @character.birth_date %>
</p>

<p>
  <strong>Death date:</strong>
  <%= @character.death_date %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @character.faction.name %>
</p>

<p>
  <strong>Birth location:</strong>
  <%= @character.birth_location %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @character.bio %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>